env = Environment(tools = ['default','chicken'], toolpath = ['/home/john/mingw/scons-tools'])
env.Append(SWIGFLAGS=["-chicken"])

cppPATH = ["/usr/local/include","/usr/include/glib-2.0","/usr/lib/glib-2.0/include"]
env.Append(CHICKENFLAGS = '-dynamic -feature chicken-compile-shared')

chicken_files = env.ChickenFile(["chicken_glib.scm","chicken_wrap_glib.scm","GObject.scm"])

env.SharedLibrary("chicken-glib",
		['chicken-glib.i']+chicken_files,
		CPPPATH = cppPATH)