;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkArrow))
(define GtkArrow (GtkMisc 'clone))
(GtkArrow 'add-method-slot! 'set (lambda (self resend  arrow_type shadow_type) 
	(gtk-arrow-set (self 'this)  arrow_type shadow_type)))
(GtkArrow 'add-method-slot! 'new (lambda (self resend  arrow_type shadow_type) 
	(self 'set-this! (gtk-arrow-new  arrow_type shadow_type))))
