;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkAspectFrame))
(define GtkAspectFrame (GtkFrame 'clone))
(GtkAspectFrame 'add-method-slot! 'set (lambda (self resend  xalign yalign ratio obey_child) 
	(gtk-aspect-frame-set (self 'this)  xalign yalign ratio obey_child)))
(GtkAspectFrame 'add-method-slot! 'new (lambda (self resend  label xalign yalign ratio obey_child) 
	(self 'set-this! (gtk-aspect-frame-new  label xalign yalign ratio obey_child))))
