;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkBin))
(define GtkBin (GtkContainer 'clone))
(GtkBin 'add-method-slot! 'get_child (lambda (self resend ) 
	(gtk-bin-get-child (self 'this) )))
