;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkCellRendererProgress))
(define GtkCellRendererProgress (GtkCellRenderer 'clone))
(GtkCellRendererProgress 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-cell-renderer-progress-new ))))
