;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkCellRendererToggle))
(define GtkCellRendererToggle (GtkCellRenderer 'clone))
(GtkCellRendererToggle 'add-method-slot! 'get_radio (lambda (self resend ) 
	(gtk-cell-renderer-toggle-get-radio (self 'this) )))
(GtkCellRendererToggle 'add-method-slot! 'set_radio (lambda (self resend  radio) 
	(gtk-cell-renderer-toggle-set-radio (self 'this)  radio)))
(GtkCellRendererToggle 'add-method-slot! 'get_active (lambda (self resend ) 
	(gtk-cell-renderer-toggle-get-active (self 'this) )))
(GtkCellRendererToggle 'add-method-slot! 'set_active (lambda (self resend  setting) 
	(gtk-cell-renderer-toggle-set-active (self 'this)  setting)))
(GtkCellRendererToggle 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-cell-renderer-toggle-new ))))
