;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkCellRendererCombo))
(define GtkCellRendererCombo (GtkCellRendererText 'clone))
(GtkCellRendererCombo 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-cell-renderer-combo-new ))))
