;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkColorSelectionDialog))
(define GtkColorSelectionDialog (GtkDialog 'clone))
(GtkColorSelectionDialog 'add-method-slot! 'new (lambda (self resend  title) 
	(self 'set-this! (gtk-color-selection-dialog-new  title))))
