;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkCellRendererText))
(define GtkCellRendererText (GtkCellRenderer 'clone))
(GtkCellRendererText 'add-method-slot! 'set_fixed_height_from_font (lambda (self resend  number_of_rows) 
	(gtk-cell-renderer-text-set-fixed-height-from-font (self 'this)  number_of_rows)))
(GtkCellRendererText 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-cell-renderer-text-new ))))
