;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkCellRendererPixbuf))
(define GtkCellRendererPixbuf (GtkCellRenderer 'clone))
(GtkCellRendererPixbuf 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-cell-renderer-pixbuf-new ))))
