;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkCheckButton))
(define GtkCheckButton (GtkToggleButton 'clone))
(GtkCheckButton 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-check-button-new ))))
