;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkDrawingArea))
(define GtkDrawingArea (GtkWidget 'clone))
(GtkDrawingArea 'add-method-slot! 'size (lambda (self resend  width height) 
	(gtk-drawing-area-size (self 'this)  width height)))
(GtkDrawingArea 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-drawing-area-new ))))
