;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkFixed))
(define GtkFixed (GtkContainer 'clone))
(GtkFixed 'add-method-slot! 'put (lambda (self resend  widget x y) 
	(gtk-fixed-put (self 'this)  widget x y)))
(GtkFixed 'add-method-slot! 'move (lambda (self resend  widget x y) 
	(gtk-fixed-move (self 'this)  widget x y)))
(GtkFixed 'add-method-slot! 'set_has_window (lambda (self resend  has_window) 
	(gtk-fixed-set-has-window (self 'this)  has_window)))
(GtkFixed 'add-method-slot! 'get_has_window (lambda (self resend ) 
	(gtk-fixed-get-has-window (self 'this) )))
(GtkFixed 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-fixed-new ))))
