;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkFileChooserButton))
(define GtkFileChooserButton (GtkHBox 'clone))
(GtkFileChooserButton 'add-method-slot! 'get_title (lambda (self resend ) 
	(gtk-file-chooser-button-get-title (self 'this) )))
(GtkFileChooserButton 'add-method-slot! 'set_title (lambda (self resend  title) 
	(gtk-file-chooser-button-set-title (self 'this)  title)))
(GtkFileChooserButton 'add-method-slot! 'get_width_chars (lambda (self resend ) 
	(gtk-file-chooser-button-get-width-chars (self 'this) )))
(GtkFileChooserButton 'add-method-slot! 'set_width_chars (lambda (self resend  n_chars) 
	(gtk-file-chooser-button-set-width-chars (self 'this)  n_chars)))
(GtkFileChooserButton 'add-method-slot! 'new (lambda (self resend  title action) 
	(self 'set-this! (gtk-file-chooser-button-new  title action))))
