;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkFileChooserDialog))
(define GtkFileChooserDialog (GtkDialog 'clone))
(GtkFileChooserDialog 'add-method-slot! 'new (lambda (self resend  title parent action first_button_text) 
	(self 'set-this! (gtk-file-chooser-dialog-new  title parent action first_button_text))))
