;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkFileChooserWidget))
(define GtkFileChooserWidget (GtkVBox 'clone))
(GtkFileChooserWidget 'add-method-slot! 'new (lambda (self resend  action) 
	(self 'set-this! (gtk-file-chooser-widget-new  action))))
