;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkGammaCurve))
(define GtkGammaCurve (GtkVBox 'clone))
(GtkGammaCurve 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-gamma-curve-new ))))
