;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkInvisible))
(define GtkInvisible (GtkWidget 'clone))
(GtkInvisible 'add-method-slot! 'set_screen (lambda (self resend  screen) 
	(gtk-invisible-set-screen (self 'this)  screen)))
(GtkInvisible 'add-method-slot! 'get_screen (lambda (self resend ) 
	(gtk-invisible-get-screen (self 'this) )))
(GtkInvisible 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-invisible-new ))))
