;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkInputDialog))
(define GtkInputDialog (GtkDialog 'clone))
(GtkInputDialog 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-input-dialog-new ))))
