;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkImageMenuItem))
(define GtkImageMenuItem (GtkMenuItem 'clone))
(GtkImageMenuItem 'add-method-slot! 'set_image (lambda (self resend  image) 
	(gtk-image-menu-item-set-image (self 'this)  image)))
(GtkImageMenuItem 'add-method-slot! 'get_image (lambda (self resend ) 
	(gtk-image-menu-item-get-image (self 'this) )))
(GtkImageMenuItem 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-image-menu-item-new ))))
