;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkItem))
(define GtkItem (GtkBin 'clone))
(GtkItem 'add-method-slot! 'select (lambda (self resend ) 
	(gtk-item-select (self 'this) )))
(GtkItem 'add-method-slot! 'deselect (lambda (self resend ) 
	(gtk-item-deselect (self 'this) )))
(GtkItem 'add-method-slot! 'toggle (lambda (self resend ) 
	(gtk-item-toggle (self 'this) )))
