;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkListItem))
(define GtkListItem (GtkItem 'clone))
(GtkListItem 'add-method-slot! 'select (lambda (self resend ) 
	(gtk-list-item-select (self 'this) )))
(GtkListItem 'add-method-slot! 'deselect (lambda (self resend ) 
	(gtk-list-item-deselect (self 'this) )))
(GtkListItem 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-list-item-new ))))
