;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkMessageDialog))
(define GtkMessageDialog (GtkDialog 'clone))
(GtkMessageDialog 'add-method-slot! 'set_markup (lambda (self resend  str) 
	(gtk-message-dialog-set-markup (self 'this)  str)))
(GtkMessageDialog 'add-method-slot! 'format_secondary_text (lambda (self resend  message_format) 
	(gtk-message-dialog-format-secondary-text (self 'this)  message_format)))
(GtkMessageDialog 'add-method-slot! 'format_secondary_markup (lambda (self resend  message_format) 
	(gtk-message-dialog-format-secondary-markup (self 'this)  message_format)))
(GtkMessageDialog 'add-method-slot! 'new (lambda (self resend  parent flags type buttons message_format) 
	(self 'set-this! (gtk-message-dialog-new  parent flags type buttons message_format))))
