;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkMenuToolButton))
(define GtkMenuToolButton (GtkToolButton 'clone))
(GtkMenuToolButton 'add-method-slot! 'set_menu (lambda (self resend  menu) 
	(gtk-menu-tool-button-set-menu (self 'this)  menu)))
(GtkMenuToolButton 'add-method-slot! 'get_menu (lambda (self resend ) 
	(gtk-menu-tool-button-get-menu (self 'this) )))
(GtkMenuToolButton 'add-method-slot! 'set_arrow_tooltip (lambda (self resend  tooltips tip_text tip_private) 
	(gtk-menu-tool-button-set-arrow-tooltip (self 'this)  tooltips tip_text tip_private)))
(GtkMenuToolButton 'add-method-slot! 'new (lambda (self resend  icon_widget label) 
	(self 'set-this! (gtk-menu-tool-button-new  icon_widget label))))
