;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkMisc))
(define GtkMisc (GtkWidget 'clone))
(GtkMisc 'add-method-slot! 'set_alignment (lambda (self resend  xalign yalign) 
	(gtk-misc-set-alignment (self 'this)  xalign yalign)))
(GtkMisc 'add-method-slot! 'get_alignment (lambda (self resend  xalign yalign) 
	(gtk-misc-get-alignment (self 'this)  xalign yalign)))
(GtkMisc 'add-method-slot! 'set_padding (lambda (self resend  xpad ypad) 
	(gtk-misc-set-padding (self 'this)  xpad ypad)))
(GtkMisc 'add-method-slot! 'get_padding (lambda (self resend  xpad ypad) 
	(gtk-misc-get-padding (self 'this)  xpad ypad)))
