;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkOldEditable))
(define GtkOldEditable (GtkWidget 'clone))
(GtkOldEditable 'add-method-slot! 'claim_selection (lambda (self resend  claim time_) 
	(gtk-old-editable-claim-selection (self 'this)  claim time_)))
(GtkOldEditable 'add-method-slot! 'changed (lambda (self resend ) 
	(gtk-old-editable-changed (self 'this) )))
