;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkPixmap))
(define GtkPixmap (GtkMisc 'clone))
(GtkPixmap 'add-method-slot! 'set (lambda (self resend  val mask) 
	(gtk-pixmap-set (self 'this)  val mask)))
(GtkPixmap 'add-method-slot! 'get (lambda (self resend  val mask) 
	(gtk-pixmap-get (self 'this)  val mask)))
(GtkPixmap 'add-method-slot! 'set_build_insensitive (lambda (self resend  build) 
	(gtk-pixmap-set-build-insensitive (self 'this)  build)))
(GtkPixmap 'add-method-slot! 'new (lambda (self resend  pixmap mask) 
	(self 'set-this! (gtk-pixmap-new  pixmap mask))))
