;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkRadioToolButton))
(define GtkRadioToolButton (GtkToggleToolButton 'clone))
(GtkRadioToolButton 'add-method-slot! 'new_from_widget (lambda (self resend ) 
	(gtk-radio-tool-button-new-from-widget (self 'this) )))
(GtkRadioToolButton 'add-method-slot! 'new_with_stock_from_widget (lambda (self resend  stock_id) 
	(gtk-radio-tool-button-new-with-stock-from-widget (self 'this)  stock_id)))
(GtkRadioToolButton 'add-method-slot! 'get_group (lambda (self resend ) 
	(gtk-radio-tool-button-get-group (self 'this) )))
(GtkRadioToolButton 'add-method-slot! 'set_group (lambda (self resend  group) 
	(gtk-radio-tool-button-set-group (self 'this)  group)))
(GtkRadioToolButton 'add-method-slot! 'new (lambda (self resend  group) 
	(self 'set-this! (gtk-radio-tool-button-new  group))))
