;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkRcStyle))
(define GtkRcStyle (GObject 'clone))
(GtkRcStyle 'add-method-slot! 'copy (lambda (self resend ) 
	(gtk-rc-style-copy (self 'this) )))
(GtkRcStyle 'add-method-slot! 'ref (lambda (self resend ) 
	(gtk-rc-style-ref (self 'this) )))
(GtkRcStyle 'add-method-slot! 'unref (lambda (self resend ) 
	(gtk-rc-style-unref (self 'this) )))
(GtkRcStyle 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-rc-style-new ))))
