;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkSocket))
(define GtkSocket (GtkContainer 'clone))
(GtkSocket 'add-method-slot! 'add_id (lambda (self resend  window_id) 
	(gtk-socket-add-id (self 'this)  window_id)))
(GtkSocket 'add-method-slot! 'get_id (lambda (self resend ) 
	(gtk-socket-get-id (self 'this) )))
(GtkSocket 'add-method-slot! 'steal (lambda (self resend  wid) 
	(gtk-socket-steal (self 'this)  wid)))
(GtkSocket 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-socket-new ))))
