;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkSettings))
(define GtkSettings (GObject 'clone))
(GtkSettings 'add-method-slot! 'set_property_value (lambda (self resend  name svalue) 
	(gtk-settings-set-property-value (self 'this)  name svalue)))
(GtkSettings 'add-method-slot! 'set_string_property (lambda (self resend  name v_string origin) 
	(gtk-settings-set-string-property (self 'this)  name v_string origin)))
(GtkSettings 'add-method-slot! 'set_long_property (lambda (self resend  name v_long origin) 
	(gtk-settings-set-long-property (self 'this)  name v_long origin)))
(GtkSettings 'add-method-slot! 'set_double_property (lambda (self resend  name v_double origin) 
	(gtk-settings-set-double-property (self 'this)  name v_double origin)))
