;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkSeparatorMenuItem))
(define GtkSeparatorMenuItem (GtkMenuItem 'clone))
(GtkSeparatorMenuItem 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-separator-menu-item-new ))))
