;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkSeparatorToolItem))
(define GtkSeparatorToolItem (GtkToolItem 'clone))
(GtkSeparatorToolItem 'add-method-slot! 'get_draw (lambda (self resend ) 
	(gtk-separator-tool-item-get-draw (self 'this) )))
(GtkSeparatorToolItem 'add-method-slot! 'set_draw (lambda (self resend  draw) 
	(gtk-separator-tool-item-set-draw (self 'this)  draw)))
(GtkSeparatorToolItem 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-separator-tool-item-new ))))
