;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkToggleToolButton))
(define GtkToggleToolButton (GtkToolButton 'clone))
(GtkToggleToolButton 'add-method-slot! 'set_active (lambda (self resend  is_active) 
	(gtk-toggle-tool-button-set-active (self 'this)  is_active)))
(GtkToggleToolButton 'add-method-slot! 'get_active (lambda (self resend ) 
	(gtk-toggle-tool-button-get-active (self 'this) )))
(GtkToggleToolButton 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-toggle-tool-button-new ))))
