;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkTearoffMenuItem))
(define GtkTearoffMenuItem (GtkMenuItem 'clone))
(GtkTearoffMenuItem 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-tearoff-menu-item-new ))))
