;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkTextTag))
(define GtkTextTag (GObject 'clone))
(GtkTextTag 'add-method-slot! 'get_priority (lambda (self resend ) 
	(gtk-text-tag-get-priority (self 'this) )))
(GtkTextTag 'add-method-slot! 'set_priority (lambda (self resend  priority) 
	(gtk-text-tag-set-priority (self 'this)  priority)))
(GtkTextTag 'add-method-slot! 'event (lambda (self resend  event_object event iter) 
	(gtk-text-tag-event (self 'this)  event_object event iter)))
(GtkTextTag 'add-method-slot! 'new (lambda (self resend  name) 
	(self 'set-this! (gtk-text-tag-new  name))))
