;**********************************************
;DO NOT MODIFY GENERATED BY make-proto-tree.scm
(declare (unit GtkWindowGroup))
(define GtkWindowGroup (GObject 'clone))
(GtkWindowGroup 'add-method-slot! 'add_window (lambda (self resend  window) 
	(gtk-window-group-add-window (self 'this)  window)))
(GtkWindowGroup 'add-method-slot! 'remove_window (lambda (self resend  window) 
	(gtk-window-group-remove-window (self 'this)  window)))
(GtkWindowGroup 'add-method-slot! 'new (lambda (self resend ) 
	(self 'set-this! (gtk-window-group-new ))))
