import glob
env = Environment(tools = ['default','chicken'], toolpath = ['/home/john/mingw/scons-tools'])
env.Append(SWIGFLAGS=["-chicken"])
#get proper include paths with chicken-gtk$ pkg-config --cflags-only-I gtk+-2.0
"""
-I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
"""
gtk_PATH = """
-I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
""".split()
gtk_PATH = map((lambda x : x[2:]),gtk_PATH)
cppPATH = ["/usr/local/include"] + gtk_PATH

ccFlags = "-DGTK_ENABLE_BROKEN"
env.Append(CHICKENFLAGS = '-dynamic -feature chicken-compile-shared')

genny_scm_files = env.ChickenFile(glob.glob("scm/*.scm"))
all_files = ['chicken-gtk.i'] + genny_scm_files
env.SharedLibrary("chicken-gtk",all_files,CPPPATH = cppPATH,CCFLAGS = ccFlags.split())