(load-library 'chicken-gtk "./libchicken-gtk.so")
(define (hello) (display "hello") (newline))
(define w (GtkWindow 'clone))
(w 'new WindowType.toplevel)
(define b (GtkButton 'clone))
(b 'new)
(b 'set_label "my button")
(b 'connect-signal "clicked" hello)
(w 'add (b 'this))
(w 'show_all)
(gtk-main)
